packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - lmdb
  - msgpackr-extract
  - protobufjs
  - sharp
